FROM httpd:2.4.33-alpine
RUN apk update; \
    apk upgrade; \
	apk add openssl;

RUN openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj \
    "/C=BR/ST=DF/L=Taguatinga/O=RISE/CN=localhost" \
    -keyout /usr/local/apache2/conf/server.key -out /usr/local/apache2/conf/server.crt

# Modules
RUN sed -i '/LoadModule deflate_module/s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/LoadModule proxy_module/s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/LoadModule proxy_fcgi_module/s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/LoadModule rewrite_module/s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/LoadModule socache_shmcb_module/s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/LoadModule ssl_module modules/s/^#//g' /usr/local/apache2/conf/httpd.conf
#RUN a2enmod headers

# Copy apache vhost file to proxy php requests to php-fpm container
COPY php.conf /usr/local/apache2/conf/php.conf
RUN echo "Include /usr/local/apache2/conf/php.conf" >> /usr/local/apache2/conf/httpd.conf

COPY php-ssl.conf /usr/local/apache2/conf/php-ssl.conf
RUN echo "Include /usr/local/apache2/conf/php-ssl.conf" >> /usr/local/apache2/conf/httpd.conf
