name: CI

on: [push]

env:
  BADGE_COLOR: orange
  BADGE_PERCENT: 81

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_version: '7.4'
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
    - uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        configuration: tests/phpunit.xml
        bootstrap: tests/bootstrap.php
        php_extensions: xdebug
        args: --coverage-text
        memory_limit: 256M
    - uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: c941c93c26d8b0f8355afef39db4e148
        filename: phpunit__${{ env.BRANCH }}.json
        label: Test Coverage
        message: ${{ env.BADGE_PERCENT }}%
        color: ${{ env.BADGE_COLOR }}
        namedLogo: phpUnit
    - name: refresh coverage badge
      uses: fjogeleit/http-request-action@master
      with:
        url: https://camo.githubusercontent.com/c377baa98bcf2d04bda7d5eab2d5924c718b0cd8d2af421ec9a846c0ce631898/68747470733a2f2f696d672e736869656c64732e696f2f656e64706f696e743f75726c3d68747470733a2f2f676973742e67697468756275736572636f6e74656e742e636f6d2f6361696f666c7563656e612f63393431633933633236643862306638333535616665663339646234653134382f7261772f706870756e69745f5f2e6a736f6e
        method: PURGE