name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_version: '7.4'
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
    - uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        configuration: tests/phpunit.xml
        bootstrap: tests/bootstrap.php
        php_extensions: xdebug
        args: --coverage-text=./tests/.phpunit.cache/code-coverage/clover.txt
        memory_limit: 256M
    # Only run the coverage once
    - name: Get Coverage for badge
      run: |
        #SUMMARY="$(npm test -- --coverageReporters='text-summary' | tail -2 | head -1)"
        #TOKENS=($SUMMARY)
        ## process.env.COVERAGE = '31.93%';
        #echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

        ## var REF = 'refs/pull/27/merge.json';
        #REF=${{ github.ref }}
        ## console.log('github.ref: ' + REF);
        #echo "github.ref: $REF"
        ## var PATHS = REF.split('/');
        #IFS='/' read -ra PATHS <<< "$REF"
        ## var BRANCH_NAME = PATHS[1] + '_' + PATHS[2];
        #BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        ## console.log(BRANCH_NAME); // 'pull_27'
        #echo $BRANCH_NAME
        ## process.env.BRANCH = 'pull_27';
        #echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

        COVERAGE_MESSAGE="$(cat ./tests/.phpunit.cache/code-coverage/clover.txt | grep Lines: | head -1 | grep -Po '\d+?(\.\d+)%')"
        echo "COVERAGE_MESSAGE=$(echo ${COVERAGE_MESSAGE})" >> $GITHUB_ENV
        COVERAGE_VALUE="$(echo ${COVERAGE_MESSAGE} | grep -Po '\d+?(\.\d+)')"
        echo "COVERAGE_VALUE=$(echo ${COVERAGE_VALUE})" >> $GITHUB_ENV
        echo ${COVERAGE_MESSAGE}
        echo ${COVERAGE_VALUE}
        echo ${GITHUB_REF##*/}
    - uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: c941c93c26d8b0f8355afef39db4e148
        filename: phpunit__${{ env.BRANCH }}.json
        label: Test Coverage
        message: ${{ env.COVERAGE_MESSAGE }}
        namedLogo: phpUnit
        valColorRange: ${{ env.COVERAGE_VALUE }}
        maxColorRange: 100
        minColorRange: 0
    - name: refresh coverage badge
      uses: fjogeleit/http-request-action@master
      with:
        url: https://camo.githubusercontent.com/c377baa98bcf2d04bda7d5eab2d5924c718b0cd8d2af421ec9a846c0ce631898/68747470733a2f2f696d672e736869656c64732e696f2f656e64706f696e743f75726c3d68747470733a2f2f676973742e67697468756275736572636f6e74656e742e636f6d2f6361696f666c7563656e612f63393431633933633236643862306638333535616665663339646234653134382f7261772f706870756e69745f5f2e6a736f6e
        method: PURGE