name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_version: '7.4'
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
    - uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        configuration: tests/phpunit.xml
        bootstrap: tests/bootstrap.php
        php_extensions: xdebug
        args: --coverage-text
        memory_limit: 256M
    - uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: c941c93c26d8b0f8355afef39db4e148
        filename: phpunit__${{ env.BRANCH }}.json
        label: Test Coverage
        message: 45%
        color: green
        namedLogo: phpUnit