name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_version: '7.4'
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
    - uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        configuration: tests/phpunit.xml
        bootstrap: tests/bootstrap.php
        php_extensions: xdebug
        args: tests --coverage-clover ./coverage.xml
        memory_limit: 256M
    - uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'badge-coverage.svg'
        push_badge: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}